//
//  ScratchPatterns.swift
//  Reusable turntablism patterns for control-side pad and gesture interfaces.
//

import Foundation

/// The named turntablism technique represented by a scratch pattern.
public enum ScratchTechnique: String, CaseIterable, Hashable, Sendable {
    case baby
    case scribble
    case drag
    case forward
    case backward
    case chirp
    case flare
    case orbit
    case transform
    case crab
    case tear
    case twiddle
    case boomerang
}

/// One normalized touch sample from a circular phone/iPad platter.
public struct MobilePlatterGestureSample: Equatable, Sendable {
    /// Source-frame movement generated by the platter mapper.
    public let deltaSamples: Double
    /// Normalized contact pressure, where zero means no record contact.
    public let pressure: Double
    /// Signed source-frame velocity at this sample.
    public let velocitySamplesPerSecond: Double

    public init(
        deltaSamples: Double,
        pressure: Double,
        velocitySamplesPerSecond: Double
    ) {
        precondition(deltaSamples.isFinite, "Platter delta must be finite")
        precondition(pressure.isFinite && (0...1).contains(pressure),
                     "Platter pressure must be within 0...1")
        precondition(velocitySamplesPerSecond.isFinite, "Platter velocity must be finite")
        self.deltaSamples = deltaSamples
        self.pressure = pressure
        self.velocitySamplesPerSecond = velocitySamplesPerSecond
    }
}

/// Converts circular normalized touch coordinates into turntable movement.
///
/// The mapper uses the shortest path across the 0/1 platter seam and derives
/// velocity from host timestamps. It has no timer and performs no audio work;
/// a UI display link can feed each returned sample to `Deck.jogMoved(_:)`.
public struct MobilePlatterGestureMapper: Sendable {
    public let samplesPerRevolution: Double
    public let sensitivity: Double

    private var lastPosition: Double?
    private var lastTimestamp: TimeInterval?

    public var isTracking: Bool { lastPosition != nil }

    public init(samplesPerRevolution: Double, sensitivity: Double = 1) {
        precondition(samplesPerRevolution.isFinite && samplesPerRevolution > 0,
                     "Platter samples-per-revolution must be positive")
        precondition(sensitivity.isFinite && sensitivity > 0,
                     "Platter sensitivity must be positive")
        self.samplesPerRevolution = samplesPerRevolution
        self.sensitivity = sensitivity
    }

    /// Starts a touch track. The first sample has no movement.
    @discardableResult
    public mutating func begin(at position: Double, timestamp: TimeInterval, pressure: Double = 1)
        -> MobilePlatterGestureSample?
    {
        guard let position = normalizedPosition(position),
              normalizedPressure(pressure) != nil,
              timestamp.isFinite else { return nil }
        lastPosition = position
        lastTimestamp = timestamp
        return nil
    }

    /// Returns movement from the previous touch sample, or `nil` for invalid or
    /// non-monotonic host timestamps.
    public mutating func update(
        to position: Double,
        timestamp: TimeInterval,
        pressure: Double = 1
    ) -> MobilePlatterGestureSample? {
        guard let position = normalizedPosition(position),
              let pressure = normalizedPressure(pressure),
              timestamp.isFinite,
              let previousPosition = lastPosition,
              let previousTimestamp = lastTimestamp,
              timestamp >= previousTimestamp else { return nil }

        var rotation = position - previousPosition
        if rotation > 0.5 { rotation -= 1 }
        if rotation < -0.5 { rotation += 1 }
        let deltaSamples = rotation * samplesPerRevolution * sensitivity
        let duration = timestamp - previousTimestamp
        let velocity = duration > 0 ? deltaSamples / duration : 0
        lastPosition = position
        lastTimestamp = timestamp
        return MobilePlatterGestureSample(
            deltaSamples: deltaSamples,
            pressure: pressure,
            velocitySamplesPerSecond: velocity
        )
    }

    public mutating func end() {
        lastPosition = nil
        lastTimestamp = nil
    }

    private func normalizedPosition(_ position: Double) -> Double? {
        guard position.isFinite, (0...1).contains(position) else { return nil }
        return position == 1 ? 0 : position
    }

    private func normalizedPressure(_ pressure: Double) -> Double? {
        guard pressure.isFinite else { return nil }
        return max(0, min(1, pressure))
    }
}

/// Main-actor bridge between a mobile platter gesture and one deck.
///
/// The session owns begin/update/end ordering. Updates received before begin
/// or after end are ignored, and ending the session always releases the deck's
/// vinyl touch. This keeps UIKit/SwiftUI gesture cancellation from leaving a
/// deck stuck in scratch mode or applying a stale sample to a later touch.
@MainActor
public final class MobilePlatterGestureSession {
    public private(set) var isActive = false
    public private(set) var lastSample: MobilePlatterGestureSample?

    private let deck: Deck
    private var mapper: MobilePlatterGestureMapper

    public init(deck: Deck, samplesPerRevolution: Double, sensitivity: Double = 1) {
        self.deck = deck
        mapper = MobilePlatterGestureMapper(
            samplesPerRevolution: samplesPerRevolution,
            sensitivity: sensitivity
        )
    }

    @discardableResult
    public func begin(
        at position: Double,
        timestamp: TimeInterval,
        pressure: Double = 1
    ) -> Bool {
        guard !isActive else { return false }
        mapper.begin(at: position, timestamp: timestamp, pressure: pressure)
        guard mapper.isTracking else { return false }
        isActive = true
        lastSample = nil
        deck.jogTouchBegan(pressure: normalizedPressure(pressure))
        return true
    }

    @discardableResult
    public func update(
        to position: Double,
        timestamp: TimeInterval,
        pressure: Double = 1
    ) -> MobilePlatterGestureSample? {
        guard isActive, let sample = mapper.update(
            to: position, timestamp: timestamp, pressure: pressure
        ) else { return nil }
        lastSample = sample
        deck.jogMoved(sample)
        return sample
    }

    public func end() {
        guard isActive else { return }
        mapper.end()
        deck.jogTouchEnded()
        isActive = false
        lastSample = nil
    }

    public func cancel() {
        end()
    }

    private func normalizedPressure(_ pressure: Double) -> Double {
        guard pressure.isFinite else { return 0 }
        return max(0, min(1, pressure))
    }
}

/// One timestamped control event in a reusable scratch routine.
///
/// `deltaSamples` is a source-deck movement, suitable for passing to
/// `Deck.jogMoved(deltaSamples:)`. `faderOpen` is the desired channel-fader
/// state at that event. A zero-delta event is intentionally allowed so a
/// routine can express a fader click without moving the record. The host owns
/// the clock and applies events on the main actor; no event scheduling or
/// allocation is performed by the real-time renderer.
public struct ScratchPatternEvent: Equatable, Sendable {
    /// Elapsed time from the start of the routine, in seconds.
    public let offset: TimeInterval
    /// Signed source-deck movement in sample frames.
    public let deltaSamples: Double
    /// Whether the channel fader should be open at this event.
    public let faderOpen: Bool
    /// Normalized contact pressure captured from a mobile platter.
    public let pressure: Double
    /// Optional UI-facing description for a pad editor or guided review.
    public let label: String

    public init(
        offset: TimeInterval,
        deltaSamples: Double,
        faderOpen: Bool = true,
        label: String = "",
        pressure: Double = 1
    ) {
        precondition(offset.isFinite && offset >= 0, "Scratch event offset must be finite and non-negative")
        precondition(deltaSamples.isFinite, "Scratch event delta must be finite")
        precondition(pressure.isFinite && (0...1).contains(pressure),
                     "Scratch event pressure must be within 0...1")
        self.offset = offset
        self.deltaSamples = deltaSamples
        self.faderOpen = faderOpen
        self.label = label
        self.pressure = pressure
    }
}

/// A finite, editable timeline of record and fader movements.
public struct ScratchPattern: Equatable, Sendable {
    public let name: String
    public let technique: ScratchTechnique
    public let events: [ScratchPatternEvent]

    public init(
        name: String,
        technique: ScratchTechnique,
        events: [ScratchPatternEvent]
    ) {
        precondition(!name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                     "Scratch pattern name cannot be empty")
        for pair in zip(events, events.dropFirst()) {
            precondition(pair.0.offset <= pair.1.offset,
                         "Scratch pattern events must be in offset order")
        }
        self.name = name
        self.technique = technique
        self.events = events
    }

    /// The time at which the final event is applied, or zero for an empty pattern.
    public var duration: TimeInterval { events.last?.offset ?? 0 }

    /// The complete built-in catalog, suitable for a new Scratch Bank editor.
    public static let catalog: [ScratchPattern] = [
        .baby,
        .scribble,
        .drag,
        .forward,
        .backward,
        .chirp,
        .flare,
        .flareOneClick,
        .flareTwoClick,
        .orbit,
        .transform,
        .crab,
        .tear,
        .twiddle,
        .boomerang
    ]

    public static let baby = ScratchPattern(
        name: "Baby Scratch", technique: .baby,
        events: [
            event(0.00, 1_600, "forward"), event(0.14, -1_600, "backward"),
            event(0.28, 1_600, "forward"), event(0.42, -1_600, "backward")
        ])

    public static let scribble = ScratchPattern(
        name: "Scribble", technique: .scribble,
        events: [
            event(0.00, 420, "tight forward"), event(0.035, -420, "tight backward"),
            event(0.070, 420, "tight forward"), event(0.105, -420, "tight backward"),
            event(0.140, 420, "tight forward"), event(0.175, -420, "tight backward"),
            event(0.210, 420, "tight forward"), event(0.245, -420, "tight backward")
        ])

    public static let drag = ScratchPattern(
        name: "Drag", technique: .drag,
        events: [event(0.00, 2_400, "slow forward drag"), event(0.60, -900, "release")])

    public static let forward = ScratchPattern(
        name: "Forward", technique: .forward,
        events: [event(0.00, 2_000, "forward stroke"), event(0.16, 0, "cut")])

    public static let backward = ScratchPattern(
        name: "Backward", technique: .backward,
        events: [event(0.00, -2_000, "backward stroke"), event(0.16, 0, "cut")])

    public static let chirp = ScratchPattern(
        name: "Chirp", technique: .chirp,
        events: [
            event(0.00, 2_000, "forward"), event(0.12, 0, "close fader", open: false),
            event(0.20, -1_650, "backward"), event(0.32, 0, "open fader")
        ])

    public static let flare = ScratchPattern(
        name: "Flare", technique: .flare,
        events: [
            event(0.00, 1_200, "stroke"), event(0.07, 0, "click 1", open: false),
            event(0.10, 500, "stroke"), event(0.17, 0, "click 2", open: false),
            event(0.20, 500, "finish")
        ])

    /// A single-click flare, kept separate from the two-click form so a pad
    /// bank can expose the fader vocabulary directly.
    public static let flareOneClick = ScratchPattern(
        name: "Flare (1-click)", technique: .flare,
        events: [
            event(0.00, 1_400, "stroke"), event(0.08, 0, "click", open: false),
            event(0.13, -900, "return")
        ])

    /// The two-click form is also available by its explicit performance name;
    /// `flare` remains the compact backwards-compatible catalog entry.
    public static let flareTwoClick = ScratchPattern(
        name: "Flare (2-click)", technique: .flare,
        events: [
            event(0.00, 1_200, "stroke"), event(0.07, 0, "click 1", open: false),
            event(0.10, 500, "stroke"), event(0.17, 0, "click 2", open: false),
            event(0.20, 500, "finish")
        ])

    /// Orbit: a flare whose clicks continue over the return stroke.
    public static let orbit = ScratchPattern(
        name: "Orbit", technique: .orbit,
        events: [
            event(0.00, 1_100, "forward"), event(0.07, 0, "click 1", open: false),
            event(0.12, -700, "return"), event(0.19, 0, "click 2", open: false),
            event(0.24, -500, "return 2"), event(0.31, 0, "click 3", open: false),
            event(0.36, 900, "forward finish")
        ])

    public static let transform = ScratchPattern(
        name: "Transform", technique: .transform,
        events: [
            event(0.00, 2_600, "slow stroke"), event(0.06, 0, "tap", open: false),
            event(0.12, 0, "release"), event(0.18, 0, "tap", open: false),
            event(0.24, 0, "release"), event(0.30, 0, "tap", open: false),
            event(0.36, 0, "release")
        ])

    public static let crab = ScratchPattern(
        name: "Crab", technique: .crab,
        events: [
            event(0.00, 1_800, "stroke"), event(0.035, 0, "finger 1", open: false),
            event(0.070, 0, "finger 2"), event(0.105, 0, "finger 3", open: false),
            event(0.140, 0, "finger 4")
        ])

    public static let tear = ScratchPattern(
        name: "Tear", technique: .tear,
        events: [
            event(0.00, 1_100, "first half"), event(0.13, 700, "pause / second half"),
            event(0.28, -1_100, "return first half"), event(0.41, -700, "return second half")
        ])

    public static let twiddle = ScratchPattern(
        name: "Twiddle", technique: .twiddle,
        events: [
            event(0.00, 1_500, "stroke"), event(0.06, 0, "index click", open: false),
            event(0.10, 0, "middle click"), event(0.16, -1_500, "return")
        ])

    public static let boomerang = ScratchPattern(
        name: "Boomerang", technique: .boomerang,
        events: [
            event(0.00, 1_000, "forward 1"), event(0.08, 0, "click", open: false),
            event(0.13, 850, "forward 2"), event(0.21, 0, "click", open: false),
            event(0.26, -850, "backward 1"), event(0.34, 0, "click", open: false),
            event(0.39, -1_000, "backward 2")
        ])

    private static func event(
        _ offset: TimeInterval,
        _ deltaSamples: Double,
        _ label: String,
        open: Bool = true
    ) -> ScratchPatternEvent {
        ScratchPatternEvent(
            offset: offset,
            deltaSamples: deltaSamples,
            faderOpen: open,
            label: label
        )
    }
}

/// Mutable control-side draft for a Scratch Bank pattern.
///
/// The editor keeps events ordered by offset and only commits valid changes.
/// It is intentionally a value type so a phone/iPad editor can update a draft
/// off to the side and assign the finished `pattern` to a bank slot atomically.
public struct ScratchPatternEditor: Equatable, Sendable {
    public private(set) var name: String
    public private(set) var technique: ScratchTechnique
    public private(set) var events: [ScratchPatternEvent]

    public init(pattern: ScratchPattern) {
        name = pattern.name
        technique = pattern.technique
        events = pattern.events
    }

    public init(
        name: String,
        technique: ScratchTechnique,
        events: [ScratchPatternEvent] = []
    ) {
        precondition(!name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                     "Scratch pattern name cannot be empty")
        precondition(zip(events, events.dropFirst()).allSatisfy { $0.0.offset <= $0.1.offset },
                     "Scratch pattern events must be in offset order")
        self.name = name
        self.technique = technique
        self.events = events
    }

    /// The immutable value suitable for `ScratchBank.assign`.
    public var pattern: ScratchPattern {
        ScratchPattern(name: name, technique: technique, events: events)
    }

    @discardableResult
    public mutating func rename(_ name: String) -> Bool {
        guard !name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return false }
        self.name = name
        return true
    }

    public mutating func setTechnique(_ technique: ScratchTechnique) {
        self.technique = technique
    }

    /// Inserts an event at the requested index when it preserves timeline order.
    @discardableResult
    public mutating func insert(_ event: ScratchPatternEvent, at index: Int) -> Bool {
        guard events.indices.contains(index) || index == events.endIndex else { return false }
        if index > events.startIndex, events[index - 1].offset > event.offset { return false }
        if index < events.endIndex, event.offset > events[index].offset { return false }
        events.insert(event, at: index)
        return true
    }

    @discardableResult
    public mutating func append(_ event: ScratchPatternEvent) -> Bool {
        insert(event, at: events.endIndex)
    }

    /// Replaces an event when the replacement remains ordered with its neighbors.
    @discardableResult
    public mutating func updateEvent(at index: Int, with event: ScratchPatternEvent) -> Bool {
        guard events.indices.contains(index) else { return false }
        if index > events.startIndex, events[index - 1].offset > event.offset { return false }
        if index + 1 < events.endIndex, event.offset > events[index + 1].offset { return false }
        events[index] = event
        return true
    }

    @discardableResult
    public mutating func removeEvent(at index: Int) -> Bool {
        guard events.indices.contains(index) else { return false }
        events.remove(at: index)
        return true
    }

    public mutating func removeAllEvents() {
        events.removeAll(keepingCapacity: true)
    }
}

/// Main-actor recorder that converts timestamped live gestures into a pattern.
///
/// A display-link or gesture coordinator supplies monotonic elapsed time. The
/// recorder stores only control events and never runs on, or synchronizes with,
/// the real-time audio thread. Calling `finish()` returns `nil` for an empty
/// recording; callers can edit the returned pattern before assigning it to a
/// Scratch Bank slot.
@MainActor
public final class ScratchPatternRecorder {
    public let name: String
    public let technique: ScratchTechnique
    public private(set) var isRecording = false
    public private(set) var elapsed: TimeInterval = 0
    public private(set) var events: [ScratchPatternEvent] = []

    /// Best-effort live label for the current take. The original event stream
    /// remains authoritative and can always be corrected in the editor.
    public var recognition: ScratchTechniqueRecognition? {
        ScratchTechniqueRecognizer().recognize(events: events)
    }

    public init(name: String, technique: ScratchTechnique) {
        precondition(!name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                     "Scratch recording name cannot be empty")
        self.name = name
        self.technique = technique
    }

    public func start() {
        events.removeAll(keepingCapacity: true)
        elapsed = 0
        isRecording = true
    }

    /// Advances the recording clock without adding an event.
    @discardableResult
    public func advance(to elapsed: TimeInterval) -> Bool {
        guard isRecording, elapsed.isFinite, elapsed >= self.elapsed else { return false }
        self.elapsed = elapsed
        return true
    }

    /// Records one jog/fader sample at a monotonic host-clock timestamp.
    @discardableResult
    public func record(
        at elapsed: TimeInterval,
        deltaSamples: Double,
        faderOpen: Bool = true,
        label: String = "",
        pressure: Double = 1
    ) -> Bool {
        guard isRecording, elapsed.isFinite, elapsed >= self.elapsed,
              pressure.isFinite, (0...1).contains(pressure) else { return false }
        let event = ScratchPatternEvent(
            offset: elapsed,
            deltaSamples: deltaSamples,
            faderOpen: faderOpen,
            label: label,
            pressure: pressure
        )
        events.append(event)
        self.elapsed = elapsed
        return true
    }

    @discardableResult
    public func record(
        _ sample: MobilePlatterGestureSample,
        at elapsed: TimeInterval,
        faderOpen: Bool = true,
        label: String = ""
    ) -> Bool {
        record(
            at: elapsed,
            deltaSamples: sample.deltaSamples,
            faderOpen: faderOpen,
            label: label,
            pressure: sample.pressure
        )
    }

    /// Ends the recording and returns an immutable pattern, if it captured an event.
    public func finish() -> ScratchPattern? {
        guard isRecording else { return nil }
        isRecording = false
        guard !events.isEmpty else { return nil }
        return ScratchPattern(name: name, technique: technique, events: events)
    }

    /// Finishes the take using the deterministic control-topology recognizer.
    /// This is a convenience for a UI that wants an initial label; it does not
    /// alter the captured timing, pressure, or fader events.
    public func finishRecognized() -> ScratchPattern? {
        guard isRecording else { return nil }
        isRecording = false
        guard !events.isEmpty else { return nil }
        let detected = recognition?.technique ?? technique
        return ScratchPattern(name: name, technique: detected, events: events)
    }

    public func cancel() {
        isRecording = false
        elapsed = 0
        events.removeAll(keepingCapacity: true)
    }
}

/// Main-actor-owned eight-pad Scratch Bank.
///
/// The bank stores patterns but does not run a timer. A UI/display-link layer
/// obtains a cursor with `cursor(for:)`, advances it using elapsed time, and
/// applies the returned events to a deck and its channel fader. Keeping the
/// clock in the host makes pad triggering deterministic and avoids putting
/// Swift scheduling or allocations anywhere near the audio callback.
@MainActor
public final class ScratchBank {
    public static let slotCount = 8

    public private(set) var slots: [ScratchPattern?]
    private var players: [ObjectIdentifier: ScratchPatternPlayer] = [:]

    public init() {
        slots = Array(repeating: nil, count: Self.slotCount)
    }

    /// Assigns a pattern to a pad. Slots use the same zero-based indexing as
    /// `Deck.padPress(_:)`, so valid values are 0…7.
    @discardableResult
    public func assign(_ pattern: ScratchPattern, to slot: Int) -> Bool {
        guard slots.indices.contains(slot) else { return false }
        slots[slot] = pattern
        return true
    }

    public func pattern(at slot: Int) -> ScratchPattern? {
        guard slots.indices.contains(slot) else { return nil }
        return slots[slot]
    }

    public func editor(for slot: Int) -> ScratchPatternEditor? {
        guard let pattern = pattern(at: slot) else { return nil }
        return ScratchPatternEditor(pattern: pattern)
    }

    @discardableResult
    public func assign(_ editor: ScratchPatternEditor, to slot: Int) -> Bool {
        assign(editor.pattern, to: slot)
    }

    @discardableResult
    public func clear(slot: Int) -> Bool {
        guard slots.indices.contains(slot) else { return false }
        slots[slot] = nil
        return true
    }

    public func cursor(for slot: Int) -> ScratchPatternCursor? {
        guard let pattern = pattern(at: slot) else { return nil }
        return ScratchPatternCursor(pattern: pattern)
    }

    /// Starts a stored pattern on a deck and its corresponding channel.
    ///
    /// The first event is applied immediately. Subsequent events are advanced
    /// by `DJEngine.tickAutomation(elapsed:)` or by `HeadlessDJEngine.render`.
    /// Triggering an occupied deck cancels its previous routine first.
    @discardableResult
    public func trigger(
        _ slot: Int,
        on deck: Deck,
        channel: Channel,
        looping: Bool = false
    ) -> Bool {
        guard let pattern = pattern(at: slot), !pattern.events.isEmpty else { return false }
        stop(on: deck)
        let player = ScratchPatternPlayer(deck: deck, channel: channel)
        players[ObjectIdentifier(deck)] = player
        player.start(pattern: pattern, looping: looping)
        if !player.isActive { players[ObjectIdentifier(deck)] = nil }
        return player.isActive
    }

    /// Stops the active routine on a deck and restores its pre-pattern fader.
    public func stop(on deck: Deck) {
        let id = ObjectIdentifier(deck)
        players.removeValue(forKey: id)?.stop()
    }

    /// Stops every active routine and restores all affected channel faders.
    public func stopAll() {
        let activePlayers = Array(players.values)
        players.removeAll(keepingCapacity: true)
        activePlayers.forEach { $0.stop() }
    }

    public func isPlaying(on deck: Deck) -> Bool {
        players[ObjectIdentifier(deck)]?.isActive == true
    }

    /// Advances all active routines from the host/control clock.
    internal func advance(elapsed: TimeInterval) {
        guard elapsed.isFinite, elapsed >= 0 else { return }
        var finishedIDs: [ObjectIdentifier] = []
        for (id, player) in players {
            player.advance(elapsed: elapsed)
            if !player.isActive { finishedIDs.append(id) }
        }
        for id in finishedIDs { players[id] = nil }
    }
}

/// Control-side Scratch Bank playback for one deck/channel pair.
///
/// This object only posts the same `Deck` jog commands and `Channel` fader
/// controls used by a human gesture. It never renders audio, sleeps, or owns
/// a timer. That keeps pattern playback deterministic in tests and lets a
/// phone/iPad display link provide the clock without affecting the audio
/// callback.
@MainActor
public final class ScratchPatternPlayer {
    public private(set) var isActive = false
    public private(set) var elapsed: TimeInterval = 0
    public private(set) var pattern: ScratchPattern?
    public private(set) var looping = false

    private let deck: Deck
    private let channel: Channel
    private var cursor: ScratchPatternCursor?
    private var originalFader: Double = 1
    private var ownsJogTouch = false

    fileprivate init(deck: Deck, channel: Channel) {
        self.deck = deck
        self.channel = channel
    }

    fileprivate func start(pattern: ScratchPattern, looping: Bool) {
        stop()
        guard !pattern.events.isEmpty else { return }
        self.pattern = pattern
        self.cursor = ScratchPatternCursor(pattern: pattern)
        self.looping = looping
        self.elapsed = 0
        self.originalFader = channel.fader
        deck.jogTouchBegan()
        ownsJogTouch = true
        isActive = true
        advance(elapsed: 0)
    }

    /// Applies every event that became due during `elapsed` seconds.
    fileprivate func advance(elapsed delta: TimeInterval) {
        guard isActive, delta.isFinite, delta >= 0, var cursor, let pattern else { return }
        let duration = max(pattern.duration, 0.001)
        self.elapsed += delta

        while isActive {
            for event in cursor.advance(to: self.elapsed) {
                channel.fader = event.faderOpen ? 1 : 0
                deck.jogMoved(deltaSamples: event.deltaSamples, pressure: event.pressure)
            }
            if !cursor.isFinished { break }
            guard looping else {
                self.cursor = cursor
                finish()
                return
            }
            self.elapsed -= duration
            cursor.reset()
        }
        self.cursor = cursor
    }

    fileprivate func stop() {
        guard isActive else { return }
        finish()
    }

    private func finish() {
        if ownsJogTouch {
            deck.jogTouchEnded()
            ownsJogTouch = false
        }
        channel.fader = originalFader
        isActive = false
        looping = false
    }
}

/// Deterministic host-side cursor for driving a pattern timeline.
public struct ScratchPatternCursor: Sendable {
    public let pattern: ScratchPattern
    public private(set) var nextEventIndex: Int = 0

    public init(pattern: ScratchPattern) {
        self.pattern = pattern
    }

    public var isFinished: Bool { nextEventIndex >= pattern.events.count }

    /// Returns each event whose offset is at or before `elapsed` exactly once.
    /// Calling with an earlier time leaves the cursor unchanged.
    public mutating func advance(to elapsed: TimeInterval) -> [ScratchPatternEvent] {
        guard elapsed.isFinite, elapsed >= 0 else { return [] }
        var end = nextEventIndex
        while end < pattern.events.count, pattern.events[end].offset <= elapsed {
            end += 1
        }
        guard end > nextEventIndex else { return [] }
        let result = Array(pattern.events[nextEventIndex..<end])
        nextEventIndex = end
        return result
    }

    public mutating func reset() {
        nextEventIndex = 0
    }
}
