#!/usr/bin/env bash
#
# setup-linux.sh — install and configure the Linux and Windows cross-build
# toolchains used by parso-audio-engine.
#
# Supported host: Debian/Ubuntu x86_64 Linux.
# Installs native C/C++ tools, .NET 8, and the MinGW-w64 x86_64 GNU toolchain.
# The MinGW artifact is portability evidence; native Windows/MSVC CI remains
# the release authority for the Windows ABI and runtime.
#
# Usage:
#   ./scripts/setup-linux.sh
#   ./scripts/setup-linux.sh --no-build
#   ./scripts/setup-linux.sh --no-windows-cross-build
#   PARSO_DOTNET_CHANNEL=9.0 ./scripts/setup-linux.sh
#
# Environment overrides:
#   PARSO_DOTNET_CHANNEL      .NET SDK channel (default: 8.0)
#   PARSO_LINUX_ENV_FILE      environment file (default: ~/.parso-linux-env)
#   PARSO_LINUX_SHELL_PROFILE shell profile to update
#   PARSO_LINUX_BUILD_DIR     native build directory (default: build-linux)
#   PARSO_WINDOWS_BUILD_DIR   cross build directory (default: build-windows-cross)
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
USER_HOME="${HOME:?HOME must be set}"
DOTNET_CHANNEL="${PARSO_DOTNET_CHANNEL:-8.0}"
ENV_FILE="${PARSO_LINUX_ENV_FILE:-$USER_HOME/.parso-linux-env}"
NATIVE_BUILD_DIR="${PARSO_LINUX_BUILD_DIR:-$REPO_ROOT/build-linux}"
WINDOWS_BUILD_DIR="${PARSO_WINDOWS_BUILD_DIR:-$REPO_ROOT/build-windows-cross}"
VERIFY_BUILD=1
VERIFY_WINDOWS_CROSS_BUILD=1

die() {
    echo "error: $*" >&2
    exit 1
}

log() {
    echo "==> $*"
}

usage() {
    sed -n '1,42p' "$0"
}

while (($# > 0)); do
    case "$1" in
        --no-build)
            VERIFY_BUILD=0
            ;;
        --no-windows-cross-build)
            VERIFY_WINDOWS_CROSS_BUILD=0
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            die "unknown argument '$1' (use --help)"
            ;;
    esac
    shift
done

[ "$(uname -s)" = Linux ] || die "this script must run on Linux"
[ "$(uname -m)" = x86_64 ] || die "the current Windows cross-build targets Linux x86_64"
[ -f /etc/os-release ] || die "cannot identify the Linux distribution"
# shellcheck disable=SC1091
. /etc/os-release
case "${ID:-}" in
    ubuntu|debian) ;;
    *) die "supported distributions are Debian and Ubuntu; install the listed tools manually on ${ID:-unknown}" ;;
esac

APT_PREFIX=()
if [ "$(id -u)" -ne 0 ]; then
    command -v sudo >/dev/null 2>&1 || die "sudo is required to install Linux packages"
    APT_PREFIX=(sudo)
fi

apt_install() {
    "${APT_PREFIX[@]}" apt-get install -y "$@"
}

install_dotnet_repository() {
    local distro="$1"
    local version="$2"
    local repo_package
    repo_package="$(mktemp "${TMPDIR:-/tmp}/packages-microsoft-prod.XXXXXX.deb")"
    trap 'rm -f "$repo_package"' RETURN
    log "Installing the Microsoft package repository for $distro $version"
    curl -fL --retry 3 --retry-delay 2 \
        -o "$repo_package" \
        "https://packages.microsoft.com/config/$distro/$version/packages-microsoft-prod.deb"
    "${APT_PREFIX[@]}" dpkg -i "$repo_package"
    rm -f "$repo_package"
    trap - RETURN
}

install_dependencies() {
    command -v apt-get >/dev/null 2>&1 || die "apt-get is required"
    log "Updating Debian/Ubuntu package indexes"
    "${APT_PREFIX[@]}" apt-get update
    log "Installing Linux native and Windows cross-build prerequisites"
    apt_install \
        build-essential \
        cmake \
        ninja-build \
        pkg-config \
        curl \
        git \
        unzip \
        zip \
        ca-certificates \
        file \
        mingw-w64 \
        gcc-mingw-w64-x86-64 \
        g++-mingw-w64-x86-64 \
        binutils-mingw-w64-x86-64

    if ! command -v dotnet >/dev/null 2>&1; then
        # Prefer the distribution feed when it already provides the requested
        # SDK. Microsoft documents this path for supported Ubuntu releases;
        # add Microsoft's feed only when Debian or an older Ubuntu lacks it.
        if ! apt-cache show "dotnet-sdk-${DOTNET_CHANNEL}" >/dev/null 2>&1; then
            install_dotnet_repository "$ID" "${VERSION_ID:?VERSION_ID is required}"
            "${APT_PREFIX[@]}" apt-get update
        fi
        apt_install "dotnet-sdk-${DOTNET_CHANNEL}"
    fi
}

verify_tools() {
    command -v cmake >/dev/null 2>&1 || die "cmake is not available"
    command -v ninja >/dev/null 2>&1 || die "ninja is not available"
    command -v x86_64-w64-mingw32-g++ >/dev/null 2>&1 || die "MinGW-w64 x86_64 compiler is not available"
    command -v dotnet >/dev/null 2>&1 || die ".NET SDK is not available"
    cmake --version | head -n 1
    ninja --version
    x86_64-w64-mingw32-g++ --version | head -n 1
    dotnet --version
}

write_environment() {
    mkdir -p "$(dirname "$ENV_FILE")"
    {
        cat <<'EOF'
# Generated by parso-audio-engine/scripts/setup-linux.sh
EOF
        printf 'export PARSO_WINDOWS_TOOLCHAIN_FILE=%q\n' "$REPO_ROOT/cmake/toolchains/windows-mingw-x86_64.cmake"
        printf 'export PARSO_WINDOWS_TRIPLE=%q\n' 'x86_64-w64-mingw32'
        printf 'export PARSO_DOTNET_CHANNEL=%q\n' "$DOTNET_CHANNEL"
        printf 'export PARSO_LINUX_BUILD_DIR=%q\n' "$NATIVE_BUILD_DIR"
        printf 'export PARSO_WINDOWS_BUILD_DIR=%q\n' "$WINDOWS_BUILD_DIR"
    } > "$ENV_FILE"
    chmod 644 "$ENV_FILE"

    local shell_profile="${PARSO_LINUX_SHELL_PROFILE:-}"
    if [ -z "$shell_profile" ]; then
        case "${SHELL:-}" in
            */zsh) shell_profile="$USER_HOME/.zshrc" ;;
            *) shell_profile="$USER_HOME/.bashrc" ;;
        esac
    fi
    local profile_line="[ -f \"$ENV_FILE\" ] && . \"$ENV_FILE\""
    touch "$shell_profile"
    if ! grep -Fqx "$profile_line" "$shell_profile" 2>/dev/null; then
        {
            echo
            echo "# parso-audio-engine Linux/Windows toolchains"
            echo "$profile_line"
        } >> "$shell_profile"
    fi

    # shellcheck disable=SC1090
    . "$ENV_FILE"
    log "Environment configured in $ENV_FILE"
}

build_native_linux() {
    log "Building and testing native Linux targets"
    cmake -S "$REPO_ROOT" -B "$NATIVE_BUILD_DIR" -G Ninja \
        -DPARSO_BUILD_TESTS=ON \
        -DPARSO_BUILD_SHARED_API=ON \
        -DCMAKE_BUILD_TYPE=Release
    cmake --build "$NATIVE_BUILD_DIR" --parallel
    ctest --test-dir "$NATIVE_BUILD_DIR" --output-on-failure
}

build_windows_cross() {
    log "Cross-building Windows GNU ABI targets"
    cmake -S "$REPO_ROOT" -B "$WINDOWS_BUILD_DIR" -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE="$REPO_ROOT/cmake/toolchains/windows-mingw-x86_64.cmake" \
        -DPARSO_BUILD_TESTS=OFF \
        -DPARSO_BUILD_SHARED_API=ON \
        -DCMAKE_BUILD_TYPE=Release
    cmake --build "$WINDOWS_BUILD_DIR" --parallel
    [ -f "$WINDOWS_BUILD_DIR/parso.dll" ] || die "cross-build did not produce parso.dll"
    file "$WINDOWS_BUILD_DIR/parso.dll" 2>/dev/null || true
}

build_dotnet_cross() {
    log "Cross-compiling the Windows-targeted C# consumer on Linux"
    dotnet build "$REPO_ROOT/Bindings/ParsoAudioSharp.Consumer/ParsoAudioSharp.Consumer.csproj" \
        --configuration Release
}

install_dependencies
verify_tools
write_environment

if [ "$VERIFY_BUILD" -eq 1 ]; then
    build_native_linux
    build_dotnet_cross
    if [ "$VERIFY_WINDOWS_CROSS_BUILD" -eq 1 ]; then
        build_windows_cross
    fi
else
    log "Skipping build verification (--no-build)"
fi

echo
echo "Linux and Windows cross-build setup complete."
echo "  source \"$ENV_FILE\""
echo "  native build:  $NATIVE_BUILD_DIR"
echo "  Windows build: $WINDOWS_BUILD_DIR"
